Delete item
---
tags:
  - Item
parameters:
  - name: body
    in: body
    required: true
    description: The item to be deleted
    properties:
      uuid:
        type: string
        description: Item unique identifier
        default: 'e76fa12e-5840-4fd0-ab30-04f5c1698ba3'

responses:
  204:
    description: Item deleted successfully or does not exist
  401:
    description: No permissions to execute
  500:
    description: Internal server error