Get stores
---
tags:
  - Store

definitions:
  Store:
    type: array
    items:
      type: object
      properties:
        name:
          description: Store name
          type: string
        uuid:
          description: Store unique identifier
          type: string
        email:
          description: Store email
          type: string
        cif:
          description: Store CIF code
          type: string
        phone:
          description: Store phone
          type: string


responses:
  200:
    description: User stores
    schema:
      $ref: '#/definitions/Store'
  401:
    description: No permissions to execute
  500:
    description: Internal server error